"""ML-07 step 4: merge the raw records into EarthDial's chat format.

Reads   training/data/raw/*/records.jsonl
Writes  training/train.jsonl, training/heldout.jsonl, training/DATA.md

Held-out: 500 per dataset, seed 42 (master F3.2), so the before/after numbers
in training/report.md are measured on samples the adapter never saw.

Output schema is InternVL/LLaVA style, which is what EarthDial's own training
code consumes:
    {"id", "dataset", "task", "image": [...], "conversations": [...]}
"""

from __future__ import annotations

import argparse, json, random
from collections import Counter
from pathlib import Path

from satquery.models.rs_vlm import prompts

RAW = Path("training/data/raw")
OUT = Path("training")
SEED = 42
HOLDOUT_PER_DATASET = 500

SOURCES = {
    "vrsbench": ("xiang709/VRSBench", "captions + VQA, high resolution"),
    "rsvqa": ("dmarsili/RSVQA-LR-2k + RSVQA-HR-2k", "VQA, 2k curated subsets"),
    "cdvqa": ("ljx620/CDVQA", "two-image change VQA"),
    "bigearthnet": ("danielz01/BigEarthNet-S2-v1.0 (s2-rgb)", "land-cover vocabulary"),
    "bigearthnet_s1": ("torchgeo/bigearthnet V2/S1 + BigEarthNet.txt",
                       "Sentinel-1 radar VQA, real annotations joined on s1_name"),
}


def to_chat(rec: dict) -> dict | None:
    task = rec.get("task")
    images = [str(p) for p in rec.get("images") or []]
    answer = (rec.get("answer") or "").strip()
    if not images or not answer:
        return None
    try:
        human = prompts.build(task, rec.get("question", ""))
    except ValueError:
        return None
    if task == "change_vqa" and len(images) < 2:
        return None
    return {
        "id": rec["id"],
        "dataset": rec["dataset"],
        "task": task,
        "image": images,
        "conversations": [
            {"from": "human", "value": human},
            {"from": "gpt", "value": answer},
        ],
    }


def licences() -> dict:
    out = {}
    try:
        from huggingface_hub import HfApi
        api = HfApi()
        for rid in ("xiang709/VRSBench", "dmarsili/RSVQA-LR-2k", "dmarsili/RSVQA-HR-2k",
                    "ljx620/CDVQA", "danielz01/BigEarthNet-S2-v1.0",
                    "BIFOLD-BigEarthNetv2-0/BigEarthNet.txt"):
            try:
                info = api.dataset_info(rid)
                lic = (getattr(info, "card_data", None) or {}).get("license")
                out[rid] = lic or "not declared on the Hub"
            except Exception as e:
                out[rid] = f"lookup failed ({type(e).__name__})"
    except Exception as e:
        out["(all)"] = f"huggingface_hub unavailable ({type(e).__name__})"
    return out


def main(holdout):
    rng = random.Random(SEED)
    by_dataset: dict[str, list] = {}

    print("=== reading raw records ===", flush=True)
    for f in sorted(RAW.glob("*/records.jsonl")):
        rows = [json.loads(line) for line in f.read_text().splitlines() if line.strip()]
        name = f.parent.name
        by_dataset[name] = rows
        print(f"  {name:14s} {len(rows):6d} records   ({f})", flush=True)
    if not by_dataset:
        raise SystemExit("no records found under training/data/raw/*/records.jsonl")

    train, held = [], []
    print("\n=== converting + splitting ===", flush=True)
    for name, rows in by_dataset.items():
        chat = [c for c in (to_chat(r) for r in rows) if c]
        dropped = len(rows) - len(chat)
        rng.shuffle(chat)
        n = min(holdout, len(chat) // 4)
        held.extend(chat[:n])
        train.extend(chat[n:])
        print(f"  {name:14s} train {len(chat) - n:6d}  heldout {n:4d}  dropped {dropped}", flush=True)

    rng.shuffle(train)
    rng.shuffle(held)

    for path, rows in ((OUT / "train.jsonl", train), (OUT / "heldout.jsonl", held)):
        with path.open("w") as fh:
            for r in rows:
                fh.write(json.dumps(r) + "\n")
        print(f"\nWROTE {path}  ({len(rows)} rows)", flush=True)

    tasks = Counter(r["task"] for r in train)
    dsets = Counter(r["dataset"] for r in train)
    print(f"\n  train by task   : {dict(tasks)}", flush=True)
    print(f"  train by dataset: {dict(dsets)}", flush=True)

    print("\n=== two converted examples ===", flush=True)
    for r in train[:2]:
        print(json.dumps(r, indent=2)[:700], flush=True)

    lic = licences()
    md = ["# Training data (ML-07)", "",
          f"Generated by `training/prepare.py`, seed {SEED}. "
          f"{len(train)} training rows, {len(held)} held out "
          f"({holdout} per dataset, capped at a quarter of each).", "",
          "## Mix", "", "| dataset | source | records | role |", "|---|---|---|---|"]
    for name, rows in by_dataset.items():
        rid, role = SOURCES.get(name, ("?", "?"))
        md.append(f"| {name} | `{rid}` | {len(rows)} | {role} |")
    md += ["", "## Licences", "", "| dataset | licence |", "|---|---|"]
    for rid, l in lic.items():
        md.append(f"| `{rid}` | {l} |")
    md += ["", "## Decisions", "",
           "- **BigEarthNet text is generated from `labels`.** BigEarthNet ships",
           "  CORINE land-cover labels, not captions. `BigEarthNet.txt` (BIFOLD) has",
           "  9.6M real annotations but is text-only and keys on a `patch_id` that the",
           "  `danielz01` image mirror does not expose, so the two cannot be joined.",
           "  Labels supply the land-cover vocabulary, which is BigEarthNet's purpose",
           "  in this mix.",
           "- **BigEarthNet patches are 120x120 at 10 m/px** and are upscaled ~4x to",
           "  EarthDial's 448 px input. They teach vocabulary, not fine detail;",
           "  VRSBench and RSVQA supply high-resolution reasoning.",
           "- **VRSBench grounding/referring items are excluded.** Master F4.3: the",
           "  controller never asks rs_vlm for boxes or counts. That is the detector.",
           "- **RSVQA has no official Hub mirror.** The curated 2k subsets were used;",
           "  only a `validation` split exists, hence 4000 rather than 5000.",
           "- **Sentinel-1 is in the mix.** BigEarthNet S1 patches (VH/VV float)",
           "  are composited to false colour R=VV, G=VH, B=VV-VH, each stretched",
           "  2-98% to 8-bit, and joined to BigEarthNet.txt on `s1_name` so the",
           "  radar samples carry real annotations rather than generated text.",
           "- **Prompts come from `satquery/models/rs_vlm/prompts.py`**, shared with",
           "  inference, so training and run_real() cannot drift apart.", ""]
    (OUT / "DATA.md").write_text("\n".join(md))
    print(f"\nWROTE {OUT / 'DATA.md'}", flush=True)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--holdout", type=int, default=HOLDOUT_PER_DATASET)
    main(ap.parse_args().holdout)
